[environment]
cpu_count = 20
exec_env = "singularity"
free_mem = 9.2
overcommit_policy = "heuristic"
overcommit_limit = "50%"
nipype_version = "1.6.1"
templateflow_version = "0.7.2"
version = "21.0.4"

[execution]
bids_dir = "/data"
bids_database_dir = "/tmp/work/20221125-151039_3a1e6aa7-6a50-416d-803c-fb09377facc8/bids_db"
bids_description_hash = "daaabc6ebc090aa6e44c852cc440e0ba05dc1a0b43068f230ec8b7e8ca598aeb"
boilerplate_only = false
sloppy = false
debug = []
fmriprep_dir = "/out"
fs_license_file = "/opt/freesurfer/license.txt"
fs_subjects_dir = "/out/sourcedata/freesurfer"
layout = "BIDS Layout: .../data | Subjects: 36 | Sessions: 0 | Runs: 288"
log_dir = "/out/logs"
log_level = 25
low_mem = false
md_only_boilerplate = false
notrack = false
output_dir = "/out"
me_output_echos = false
output_layout = "bids"
output_spaces = "MNI152NLin6Asym:res-2 T1w"
reports_only = false
run_uuid = "20221125-151039_3a1e6aa7-6a50-416d-803c-fb09377facc8"
participant_label = [ "01",]
templateflow_home = "/home/fmriprep/.cache/templateflow"
work_dir = "/tmp/work"
write_graph = false

[workflow]
anat_only = false
aroma_err_on_warn = false
aroma_melodic_dim = -200
bold2t1w_dof = 6
bold2t1w_init = "register"
cifti_output = false
fmap_bspline = false
force_syn = false
hires = true
ignore = [ "t2w",]
longitudinal = false
medial_surface_nan = false
regressors_all_comps = false
regressors_dvars_th = 1.5
regressors_fd_th = 0.5
run_reconall = true
skull_strip_fixed_seed = false
skull_strip_template = "OASIS30ANTs"
skull_strip_t1w = "force"
slice_time_ref = 0.5
spaces = "MNI152NLin6Asym:res-2 T1w MNI152NLin2009cAsym"
topup_max_vols = 5
use_aroma = true
use_syn_sdc = false

[nipype]
crashfile_format = "txt"
get_linked_libs = false
nprocs = 20
omp_nthreads = 8
plugin = "MultiProc"
resource_monitor = false
stop_on_first_crash = false

[seeds]
master = 34382
ants = 50452
numpy = 53746

[nipype.plugin_args]
maxtasksperchild = 1
raise_insufficient = false
